In [2]:
import numpy as np
import pandas as pd
from sklearn.neighbors import KNeighborsClassifier
import nltk 
nltk.download('punkt')
from textblob import TextBlob
from sklearn.feature_extraction.text import CountVectorizer

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


#Simple text classification using NLP technique

# Loading the necessary libraries






In [ ]:
import numpy as np
import pandas as pd
from sklearn.neighbors import KNeighborsClassifier
import nltk 
nltk.download('punkt')
from textblob import TextBlob
from sklearn.feature_extraction.text import CountVectorizer

# CountVectorizer is used to create document term matrix
# I have prepared sample train and labels respectively

In [4]:
toNumeric = CountVectorizer()
train = ['I am a good person', 'She is also a nice person','But Mithun is very very bad']
y = [1,1,0]

# Prepared CSR matrix

In [24]:
train_dtm = toNumeric.fit_transform(train)

# Features in the train data

In [26]:
toNumeric.get_feature_names()

['also',
 'am',
 'bad',
 'but',
 'good',
 'is',
 'mithun',
 'nice',
 'person',
 'she',
 'very']

# Preparing document term matrix (Bag Of Words)

In [11]:
train_dtm.toarray()

array([[0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0],
       [1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0],
       [0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 2]])

In [12]:
pd.DataFrame(train_dtm.toarray(),columns = toNumeric.get_feature_names())

also  am  bad  but  good  is  mithun  nice  person  she  very
0     0   1    0    0     1   0       0     0       1    0     0
1     1   0    0    0     0   1       0     1       1    1     0
2     0   0    1    1     0   1       1     0       0    0     2

# Text Classification using KNN

In [17]:
knn = KNeighborsClassifier(n_neighbors=1)
knn.fit(train_dtm,y)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=1, p=2,
                     weights='uniform')

# KNN classification on Test data 

In [21]:
sampleTest = ['Sherin is a very bad person']
sampleTest_dtm = toNumeric.transform(sampleTest)

In [22]:
sampleTest_dtm.toarray()

array([[0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1]])

In [23]:
knn.predict(sampleTest_dtm)

array([0])

# Conclusion - Here the test data is similar to last record of train data, hence model studied ones and 0s train and matched to classify the test data